trainer:
  output_dir: null
  seed: 42
  gpus:
  - 0
  num_workers: 4
  batch_size: 1
  exp_name: books1
  project: object
  mode: train
  log_losses: true
  loggers:
  - csv
  torch_compile_mode: null
  accum_iter: 1
  pl_vars:
    max_steps: 10000
    log_every_n_steps: 5
    num_sanity_val_steps: 0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    enable_progress_bar: true
    precision: 32
    accumulate_grad_batches: 1
train_dataset:
  _target_: src.datasets.brics_static.Dataset
  opts:
    subject: books1
    root_dir: MANUS_data/books1/objects/books1
    params_dir: MANUS_data/books1/calib.object
    width: 1280
    height: 720
    resize_factor: 1.0
    bg_color: white
    near: 0.01
    far: 100
    split_ratio: 0.98
test_dataset:
  _target_: src.datasets.brics_static.TestDataset
  opts:
    resize_factor: 1.0
    color_bkgd_aug: white
    cam_path: ./data/camera_paths/real.pkl
    frame_sample_rate: 4
    test_on_train_dataset: false
    worst_cases: false
    test_on_canonical_pose: false
model:
  opts:
    sh_degree: 3
    num_gaussians: 100000
    sample_size: 300000
    position_lr_init: 0.0016
    position_lr_final: 1.6e-06
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.005
    rotation_lr: 0.001
    skinning_lr: 0.001
    percent_dense: 1.0e-05
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 500
    densify: true
    densify_from_step: 100
    densify_until_step: 50000
    densify_grad_threshold: 3.0e-05
    start_lpips_iter: 1000
    min_opacity_threshold: 0.005
    size_threshold: 20
    remove_outliers_step: 150000
    isotropic_scaling: false
    remove_seg_start: 0
    remove_seg_end: 1000
    condition_number: 0.4
  _target_: src.models.gaussian.GaussianModel
output_dir: outputs/object/books1/books1/
module:
  _target_: src.modules.object.TrainingModule
  opts: ${opts}
  mode: ${trainer.mode}
checkpoint: null
opts:
  losses:
  - rgb_loss
  - ssim_loss
  - isotropic_reg
  loss_weight:
  - 0.8
  - 0.2
  - 0.1
  model: ${model}
  train_dataset: ${train_dataset}
  test_dataset: ${test_dataset}
  trainer: ${trainer}
  output_dir: ${output_dir}
