output_dir: 
seed: 42
gpus: [0]
num_workers: 16
lr_rate: 0.0005
batch_size: 1
checkpoint: 
exp_name: test
checkpoint_expname: 
project: instant_hand
mode: train
log_losses: true
loggers: [csv] #wandb
torch_compile_mode: 
##default, reduce-overhead, and max-autotune

pl_vars:
  max_steps: 100
  log_every_n_steps: 5
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 5
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  enable_progress_bar: true 
  precision: 32
  # val_check_interval: 10